### ISSUE TITLE
ARC-CEs with SGE queues

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#2063] opened 2014-08-27 16:27 UTC
Hi,

[I tried the mailing list, but maybe this should go here.]

I am trying to enable some ARC CEs on my dirac server (v6r11p3 with v6r11p1 for Pilot, p3 didn't work).
I'm running into a problem with ARC-CEs using SGE, as ARC insists on inserting a '/' in the queue name [the way the queue names are constructed is not configurable], i.e. my queue is called "nordugrid-OGS/GE-grid.q" (the CE is cetest01.grid.hep.ph.ic.ac.uk, the actual queue name is grid.q). I cannot get dirac to accept this queue name (I tried to insert it straight forward, or with "", it doesn't recognize the "" and otherwise it treats the '/' as a delimiter).
Would it be possible to get Dirac to accept these kind of queue names as well ?

Regards,
Daniela

**Comment by fstagni** [comment] 2015-08-21 14:06
@rajanandakumar can you confirm this issue is still valid?

**Comment by rajanandakumar** [comment] 2015-08-21 14:15
It should be fixed with v6r14, using the queue parameter (coded in by Andrei now).
I am assuming here that the problem is not with DIRAC, but we should see.

**Comment by fstagni** [comment] 2015-08-21 14:19
Thanks, so I close this issue.

**Comment by sfayer** [comment] 2016-03-01 14:28
Is there any documentation for the queue parameter? We had a look but couldn't obviously see what we need to do to use it / change in the config...

Thanks,
Simon

**Comment by rajanandakumar** [comment] 2016-03-01 15:05
Hi,

I misunderstood the question when it was asked originally. This is not an ARC issue per-se, but more of a DIRAC issue on how the name of the queue is extracted (from bdii?) and stored in the configuration. In particular, I think that DIRAC does not like it if the published queue has a "/" inside the name. I do not know where exactly the problem is, but suspect it is in the bdii2cs (or equivalent) agent.

Once the name is stored, it is picked up whatever it is from the configuration. The ARC code itself assumes that the queue name is of the format

nordugrid-<Batch System name>-<Queue name>

And while trying to extract the queue name from the above, assumes that there are exactly two "-" in the concerned string. So, neither the batch system name nor the queue name should have a "-" in them.

As a temporary workaround, will it be possible to hard code the queue name within the DIRAC configuration? It is likely not used for anything else. Afaik (which is admittedly not too much), all the interaction with the CE goes through the ARC module which extracts the queue name exactly as described above.

Cheers,
Raja.

**Comment by marianne013** [comment] 2016-03-01 15:11
arc makes up the queue name using the output of qstat which returns "OSG/GE" for most (all?) SGE installs. So in principle they could replace this with another character, but this would require a change to the arc code. Right now this is not configurable on the arc side
dirac uses '/' as a delimiter in the config, that where all the trouble stems from.
Just inserting the queue as is name by hand doesn't seem to survive the configuration system.

**Comment by sfayer** [comment] 2016-03-01 15:11
Hi Raja,

Unfortunately not, DIRAC requires the queue name to be a "folder" in the configuration system and DIRAC can't handle having a "/" in the folder name (as this creates a sub-folder).

Regards,
Simon

**Comment by atsareg** [comment] 2016-03-01 15:23
I think it should be possible that the actual queue name and the corresponding configuration section name are not the same, where the actual queue name is just one of the queue parameters. This needs some modifications in various places - clients populating the CS and looking it up. Should be relatively easy to do.

**Comment by marianne013** [comment] 2016-04-15 09:55
Hi,
I was wondering if there has been any progress on this ? 

Regards,
Daniela

**Comment by fstagni** [comment] 2020-10-12 15:36
4 years later... @marianne013 @sfayer is this task still valid?

**Comment by marianne013** [comment] 2020-10-12 15:44
I think we can close it, let's just hope no other bit of grid software insist on auto generating queue names with / in.

**Closed** 2020-10-12 15:50 UTC
Labels: Bug, WMS
