### ISSUE TITLE
[v7r1] dirac-admin-kill-pilot for HTCondorCE fails

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4590] opened 2020-05-07 13:25 UTC
When I try and issue a kill pilot command for a pilot on an HTCondorCE I get the following error in the  PilotManager log:
```
2020-05-07 11:29:31 UTC WorkloadManagement/PilotManager ERROR: Uncaught exception when serving RPC Function killPilot
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/DISET/RequestHandler.py", line 282, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/PilotManagerHandler.py", line 264, in export_killPilot
    failed = killPilotsInQueues(pilotRefDict)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/WMSUtilities.py", line 189, in killPilotsInQueues
    result = ce.killJob(pilotList)
File "/opt/dirac/DIRAC/Resources/Computing/HTCondorCEComputingElement.py", line 305, in killJob
    job, _, jobID = condorIDAndPathToResultFromJobRef(jobRef)
  File "/opt/dirac/DIRAC/Resources/Computing/HTCondorCEComputingElement.py", line 86, in condorIDAndPathToResultFromJobRef
    jobURL, stamp = jobRef.split(":::")
ValueError: need more than 1 value to unpack
```

**Comment by andresailer** [comment] 2020-05-07 13:34
Added triple ticks
Which version of DIRAC?

**Comment by marianne013** [comment] 2020-05-07 13:36
v7r1

**Comment by marianne013** [comment] 2020-05-07 15:09
The same version. My HTCondor references look like this:
htcondorce://ceprod02.grid.hep.ph.ic.ac.uk/240271.0
and the command seems to be expecting a couple more ':' and numbers.

**Comment by andresailer** [comment] 2020-05-07 16:09
I reproduced the exception on lbcertifdirac

**Comment by andresailer** [comment] 2020-05-07 16:28
I think the exception also happens in v7r0, but I cannot test that.
The problem is that the function expects input like 
```
htcondorce://ceprod02.grid.hep.ph.ic.ac.uk/240271.0:::abc1234
```
In the previous implementation
https://github.com/DIRACGrid/DIRAC/commit/37b13eb83adce64cea27681dbb9386dc7f4249d2#diff-8444ae82a11c694417f5420068a743b4L55-L57
The input would also work if there were no three colons and the pilot stamp at the end.

**Comment by andresailer** [comment] 2020-05-11 08:27
Should be fixed in  v7r1p1 and v7r0p23

**Closed by andresailer** 2020-05-11 08:27 UTC
