### ISSUE TITLE
[v6r17p19] JobScheduling failing because of checkFilesToStage

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3335] opened 2017-05-10 11:16 UTC
https://github.com/DIRACGrid/DIRAC/blob/integration/StorageManagementSystem/Client/StorageManagerClient.py#L136

The StorageElement is created without vo parameter, so I get

```
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: preparing the execution of getFileMetadata
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: Attempting to perform 'getFileMetadata' operation with 1 lfns.
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: Determining if the StorageElement CERN-SRM is valid for VO
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: Determining if the StorageElement CERN-SRM is valid for getFileMetadata
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: determining status of CERN-SRM.
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: check the operation: CheckAccess
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: Filtering plugins for getFileMetadata (protocol = None ; inputProtocol = None)
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: Allowed protocol: ['srm', 'dips', 'root', 'xroot']
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: Potential protocols ['srm', 'dips', 'root', 'xroot']
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: Determining whether CERN-SRM is a local SE.
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling  DEBUG: Grid Types are: LCG, OSG, TEST
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: Plugins to be used for getFileMetadata: ['SRM2', 'XROOT']
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: Generating 1 protocol URLs for SRM2.
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]   VERB: generating url dict for 1 lfn in CERN-SRM.
2017-05-10 09:27:15 UTC WorkloadManagement/JobScheduling/SE[CERN-SRM]  DEBUG: LFN does not follow the DIRAC naming convention /ilc/prod/clic/test/350gev/hzqq/gen/00400956/000/hzqq_gen_400956_4.stdhep for /ilc/prod/clic/test/350gev/hzqq/gen/00400956/000/hzqq_gen_400956_4.stdhep
```
It is working if I add  `vo="ilc"`, so it is missing the vo parameter.

**Comment by chaen** [comment] 2017-05-10 11:39
if the vo is not specified from the parameters, the SE tries to get it from the proxy. Why is this not working ?

**Comment by andresailer** [comment] 2017-05-10 12:01
Apparently getVOFromProxyGroup fails because ```Can't find proxy ( 1101 : )``` and I don't have  "NoneExistingGroup" wiht a VO defined.

shifterProxy is set for the agent.

**Comment by fstagni** [comment] 2017-05-10 12:38
Is it something specific to v6r17p19? What about p18 or p17?

**Comment by andresailer** [comment] 2017-05-10 12:41
p18 also failed. But as there were changes in the JobScheduling I updated to p19. It used to work in v6r15.

**Comment by fstagni** [comment] 2017-05-10 12:48
I am asking, because in the latest patches of v6r17 there have been some changes with respect to JobScheduling and StorageManagerClient, you can find them in #3315 , #3304 and #3297 
So before looking specifically for "issues" on the SE level, I'd like to exclude issues there.

**Comment by chaen** [comment] 2017-05-10 14:50
The problem might be hidden in there indeed. But you don't need the NoneExistingGroup, it also takes from /DIRAC/VirtualOrganization

**Comment by andresailer** [comment] 2017-05-10 15:01
I have tested with v6r17p17, and the JobScheduling is working. Maybe the moving of the executeWithUserProxy wrapped parts?

**Comment by chaen** [comment] 2017-05-10 15:10
Yes, that is my suspicion, but I am trying to reproduce what you see

**Comment by chaen** [comment] 2017-05-10 15:24
how does your Operation section looks like ? is it /Operations/Setup or /Operations/VO/Setup ? 

In fact I don't really understand how it can work. It is a bootstrapping problem.
To set the shifter proxy, one needs to know who is the shifter. For that, we must look into the Operation section, which I suspect is divided by vo in your case. And to know the VO, either there is this global option, or there is a proxy already available. So I am a bit confused...

**Comment by andresailer** [comment] 2017-05-10 15:29
It looks like Operations/VO/Setup. ShifterProxies are defined in Operations/Defaults, at least for the VO that does all the work.

**Comment by chaen** [comment] 2017-05-10 15:43
Ok, so assuming you get the proxy, I don't understand how you cannot extract the VO from there. 

I can reproduce the behaviour to some extend: without the proxy I get the same as you. 
However, the difference between the version is that in the previous version, the SE was instantiated with the user proxy, while now it is (should be) instantiated with the Shifter proxy, and then the call performed with the user proxy. Any chance that your shifter proxy has no VOMS extension ? 

Btw, the test script:
```
from DIRAC.Core.Base.Script import parseCommandLine
import pprint
parseCommandLine()
from DIRAC.Resources.Storage.StorageElement import StorageElement

from DIRAC.Core.Utilities import Shifter

from DIRAC.Core.Security.ProxyInfo import getVOfromProxyGroup


print "BEFORE having the certificate"
print getVOfromProxyGroup()
print StorageElement('CERN-USER').getFileMetadata('/lhcb/user/c/chaen/zozo.xml')

pprint.pprint( Shifter.setupShifterProxyInEnv('DataManager') )
print "AFTER having the certificate"

print getVOfromProxyGroup()
print StorageElement('CERN-USER').getFileMetadata('/lhcb/user/c/chaen/zozo.xml')
```

This gives me
```
[chaen@localvm6 etc]$ python /tmp/test3.py
BEFORE having the certificate
{'OK': True, 'Value': ''}
{'OK': True, 'Value': {'Successful': {}, 'Failed': {'/lhcb/user/c/chaen/zozo.xml': 'LFN does not follow the DIRAC naming convention /lhcb/user/c/chaen/zozo.xml'}}}
{'OK': True,
 'Value': {'DN': '<whatever>',
           'chain': <whatever>,
           'group': 'lhcb_prmgr',
           'proxyFile': '/tmp/tmpDT9h8w',
           'username': 'whatever'}}
AFTER having the certificate
{'OK': True, 'Value': 'lhcb'}
{'OK': True, 'Value': {'Successful': {'/lhcb/user/c/chaen/zozo.xml': {'Accessible': True, 'ModTime': '2017-02-10 10:06:09', 'Executable': False, 'Links': 1, 'Writeable': False, 'Checksum': '29eddd7b', 'Readable': True, 'FileSerialNumber': 6917529027641133823, 'LastAccess': '2017-02-10 10:06:09', 'Mode': 256, 'File': True, 'Directory': False, 'UserID': 500, 'GroupID': 500, 'StatusChange': '2017-02-10 10:06:09', 'Size': 769L}}, 'Failed': {}}}
[chaen@localvm6 etc]$ 
```

**Comment by andresailer** [comment] 2017-05-11 08:31
I have been confusing issues. The executor did not have the shifterProxy. I added the shifterProxy option to the JobScheduling Executor now and it is working.

**Comment by chaen** [comment] 2017-05-11 09:42
Okay, and we do not see it thanks to this default VO flag I suppose.

**Comment by fstagni** [comment] 2017-05-12 08:34
I guess we can close this one then?

**Comment by andresailer** [comment] 2017-05-12 08:38
a) Should one write something here https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v6r17
b) What will happen for multiple VOs?

**Comment by chaen** [comment] 2017-05-12 09:03
a) Write about what ?
b) In fact, I don't see, based on what we discussed, how multiple VO setup can really work. It needs a default shifter proxy to start with, no ?

**Comment by andresailer** [comment] 2017-05-12 09:41
a) That shifterProxy might be needed for JobScheduling
b) exactly

**Comment by fstagni** [comment] 2017-05-12 10:09
I see. Were these changes that make the issue for multi-VO installations? https://github.com/DIRACGrid/DIRAC/pull/3304/commits/15bbefb51d470996be5f59ffae5e0b0347a7119e line 125 of StorageManagerCient

**Comment by andresailer** [comment] 2017-05-12 10:53
Probably. 
Because here https://github.com/DIRACGrid/DIRAC/blob/integration/StorageManagementSystem/Client/StorageManagerClient.py#L56 it takes the user and group from the job, which is VO specific.

**Comment by chaen** [comment] 2017-05-12 11:21
Yes, these changes are the responsible. 
We can add a shifterproxy, but i'd be in favour of making it optional. We have been able to measure that it is much faster without. 

More generally, how can multiVO works for agents ? When an agent will do setshifterProxy, that shifter will be looked for in /Operations/Default. So you need to define in Default all the shifters for all your VOs ?

**Comment by andresailer** [comment] 2017-05-12 11:51
If the `seObj` (https://github.com/DIRACGrid/DIRAC/commit/15bbefb51d470996be5f59ffae5e0b0347a7119e#diff-9e3fad0049c45575a101f73473d09329R113)
could be created with the userProxy as well it would pick up the VO from the user's group and there shouldn't be a need for a shifterProxy. I have no idea how that affects performance.

The more general part probably deserves its own issue.

**Comment by chaen** [comment] 2017-05-12 12:01
In fact, we narrowed down the part executed with the user proxy for performance reasons: this ```executeWithUserProxy``` creates a lock, which becomes a killer if you have a slow site. It totally kneeled LHCb down when RAL was dead. 
But in fact, setting the shifter proxy in the environment should not impact the performance providing we do not disable the ```useServerCertificate``` flag. So that should be safe from that point of view.

Can you do the PR, as I understand you already have it patched ?
However, what proxy should be used ? The DataManager proxy makes sense here, but for the rest of the job scheduling ? But after all, it does not make much difference, it is just to get the VO...

As for the more general issue, I agree, it needs its own, but LHCb will not be able to do anything about that, since we are not multiVO.

**Comment by andresailer** [comment] 2017-05-12 14:19
Well my fix at the moment is `shifterProxy=DataManager` in the ConfigSystem, which makes the executor be run with that proxy. No code changes needed. But I cannot test if this works for another VO, which I doubt.
Instead we could get the VO for the user group and instantiate the seObj with the vo parameter?

**Comment by andresailer** [comment] 2017-05-12 14:29
#3339 just adds some lookup in the configuration, no extension of the use of the proxy. This should be fine for everyone.

**Closed** 2017-05-16 09:28 UTC
