### ISSUE TITLE
Getting "directory not found" while selecting a directory through the tree browser

### ISSUE THREAD

**Issue by kazeevn** [DIRACGrid/DIRAC#2356] opened 2015-05-05 15:42 UTC
Dear DIRAC developers,

I'm sorry if that's the wrong place to report - I also tried forum, but the posting there is closed to public.

I tried to view metainformation for LFN:/lhcb/MC/2012/ALLSTREAMS.DST/00040479/0000/00040479_00000002_2.AllStreams.dst I've selected it through the file browser in the top-right pane, clicked the green button beneath it and got "directory not found" error - attached in full on the screenshot. The file
![screenshot from 2015-05-05 18 27 12](https://cloud.githubusercontent.com/assets/1529084/7476490/7635e2b4-f356-11e4-9577-b4822f12827a.png)
 exists - at least to Moore.
![Uploading Screenshot from 2015-05-05 18:27:12.png…]()

**Comment by chaen** [comment] 2015-05-05 15:56
Hi,

indeed there is a problem with the web interface for the time being. This should be fixed in the new future. Sorry about that.

Chris

**Comment by chaen** [comment] 2016-01-25 15:21
I believe I have fixed this. In any case, I can't reproduce anymore

**Closed** 2016-01-27 11:21 UTC
Labels: Bug, Web
