### ISSUE TITLE
[v6r14] Cannot uninstall Component

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2848] opened 2016-03-11 10:32 UTC
I have a machine with a "SiteDirector" and many "SiteDirectorXYZ".
Now I want to uninstall the SiteDirector so I open the dirac-admin-sysadmin-cli, set the host and do:
```
uninstall WorkloadManagement SiteDirector
```
To which I get 
```
[ERROR] Too many components match
```

The script
dirac-uninstall-component also doesn't work, it doesn't even have an option to set the host.
```
$ dirac-uninstall-component WorkloadManagement SiteDirector -o/DIRAC/Setup=ILC-Production
Given component does not exist
```

**Comment by fstagni** [comment] 2016-03-16 08:40
@zmathe please have a look at this

**Comment by zmathe** [comment] 2016-05-13 14:03
I have found the problem. The installedComponents table contains more than one row...

For example:

+-------------+--------+-----------------------+---------------------+---------------------+-------------+---------------+
| ComponentID | HostID | Instance              | InstallationTime    | UnInstallationTime  | InstalledBy | UnInstalledBy |
+-------------+--------+-----------------------+---------------------+---------------------+-------------+---------------+
|         116 |     65 | SystemAdministrator   | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         116 |     65 | SystemAdministrator   | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
|         118 |     65 | Server                | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         118 |     65 | Server                | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
|         126 |     65 | ResourceStatus        | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         126 |     65 | ResourceStatus        | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
|         134 |     65 | TransformationManager | 2015-08-27 11:02:35 | 2015-10-29 08:39:44 | NULL        | fstagni       |
|         150 |     65 | JobStateUpdate        | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         150 |     65 | JobStateUpdate        | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
|         151 |     65 | BookkeepingManager    | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         151 |     65 | BookkeepingManager    | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
|         152 |     65 | Optimizers            | 2015-08-27 11:02:35 | NULL                | NULL        | NULL          |
|         152 |     65 | Optimizers            | 2016-01-06 14:16:59 | NULL                | NULL        | NULL          |
+-------------+--------+-----------------------+---------------------+---------------------+-------------+---------------+

**Comment by andresailer** [comment] 2016-05-13 14:18
I think someone ran the insert component script twice in your case.
In my case just for the sitedirectors they all have different ComponentIDs, which then have a different "Module" in the Component table.
```
select * from InstalledComponents WHERE Instance = "SiteDirector";
+-------------+--------+--------------+---------------------+--------------------+-------------+---------------+
| ComponentID | HostID | Instance     | InstallationTime    | UnInstallationTime | InstalledBy | UnInstalledBy |
+-------------+--------+--------------+---------------------+--------------------+-------------+---------------+
|          32 |      6 | SiteDirector | 2016-02-04 12:29:11 | NULL               | sailer      | NULL          |
|          33 |      6 | SiteDirector | 2016-02-04 12:29:11 | NULL               | sailer      | NULL          |
|          34 |      6 | SiteDirector | 2016-02-04 12:29:11 | NULL               | sailer      | NULL          |
|          35 |      6 | SiteDirector | 2016-02-04 12:29:11 | NULL               | sailer      | NULL          |
|          36 |      6 | SiteDirector | 2016-02-04 12:29:12 | NULL               | sailer      | NULL          |
|          37 |      6 | SiteDirector | 2016-02-04 12:29:12 | NULL               | sailer      | NULL          |
+-------------+--------+--------------+---------------------+--------------------+-------------+---------------+
mysql> select * from Components WHERE Module like "SiteDirector%";
+-------------+--------------------+--------------------+-------+
| ComponentID | System             | Module             | Type  |
+-------------+--------------------+--------------------+-------+
|          32 | WorkloadManagement | SiteDirector       | agent |
|          33 | WorkloadManagement | SiteDirectorArc    | agent |
|          34 | WorkloadManagement | SiteDirectorCalice | agent |
|          35 | WorkloadManagement | SiteDirectorCream  | agent |
|          36 | WorkloadManagement | SiteDirectorHT     | agent |
|          37 | WorkloadManagement | SiteDirectorOSG    | agent |
+-------------+--------------------+--------------------+-------+
```
I want to uninstall the one with ComponentID 32

**Comment by zmathe** [comment] 2016-05-13 15:56
yes. It seams the scripts was executed twice. I will add an unique constraint to the table...
The problem is when you provide uninstall WorkloadManagement SiteDirector, the SystemAdministrator does not know which component has to be removed.
In your case the correct command is uninstall WorkloadManagement SiteDirector SiteDirectorArc
So you need uninstall System Instance Module
I will implement it.

**Comment by andresailer** [comment] 2016-05-13 16:05
Well the command I want is
```
uninstall WorkloadManagement SiteDirector SiteDirector
```
but the same principle applies (I want to keep the Arc one :) )
Thanks.

**Comment by fstagni** [comment] 2016-06-08 15:07
Hi, any update on this? Was this fixed?

**Comment by zmathe** [comment] 2016-06-08 15:12
Not yet.

**Comment by zmathe** [comment] 2016-07-21 08:09
I have checked and it is fixed in v6r15... But you have to uninstall all SiteDirectors one by one. For example:
uninstall WorkloadManagement SiteDirector-1
uninstall WorkloadManagement SiteDirector-2

**Comment by fstagni** [comment] 2016-07-21 08:30
@andresailer if this answer is OK for you, I'll close the task.

**Comment by andresailer** [comment] 2016-07-21 08:47
Does it also work for SiteDirector without any addition?

**Comment by zmathe** [comment] 2016-07-21 09:31
No. I do not think we want to do that, but this is my opinion. What I can propose in this case I list all components and I ask do you want to uninstall all? if yes, I uninstall all.
What do you think?

**Comment by andresailer** [comment] 2016-07-21 10:50
I don't want to uninstall all components. I have a SiteDirector called "SiteDirector" that I want to uninstall.

**Comment by zmathe** [comment] 2016-07-21 11:31
okay. This works:
[lbtestvobox2]> uninstall  WorkloadManagement SiteDirector
Remove logs? y/[n] :
y
Successfully uninstalled WorkloadManagement/SiteDirector

**Comment by andresailer** [comment] 2016-07-21 11:52
Ok, thanks for checking that, too. Then we can close this issue as solved.

**Comment by andresailer** [comment] 2016-08-05 07:33
Please re-open this issue, it still doesn't work in v6r15p10
```
[voilcdirac02.cern.ch]> uninstall WorkloadManagement SiteDirector
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: Discovering URL for service Framework/ComponentMonitoring -> dips://voilcdirac03.cern.ch:9190/Framework/ComponentMonitoring
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: Connecting to: dips://voilcdirac03.cern.ch:9190/Framework/ComponentMonitoring
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: Using proxy /tmp/x509up_u45181
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]   VERB: Connection timeout set to:  1
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG:  Authenticated peer (/DC=ch/DC=cern/OU=computers/CN=voilcdirac03.cern.ch)
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: New session connecting to server at ('voilcdirac03.cern.ch', 9190)
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: New connection -> 128.142.152.229:9190
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  DEBUG: Closing socket
2016-08-05 07:33:23 UTC dirac-admin-sysadmin-cli[L5dG]  ERROR: [ERROR] Too many components match
```

**Comment by andresailer** [comment] 2016-08-05 07:37
Maybe reproduce install
SiteDirector
SiteDirector-1
and then uninstall SiteDirector
Thanks

**Comment by zmathe** [comment] 2016-08-05 07:41
uninstall WorkloadManagement SiteDirector-1
uninstall WorkloadManagement SiteDirector

**Comment by andresailer** [comment] 2016-08-05 07:45
So you reproduced the issue?

**Comment by zmathe** [comment] 2016-08-05 07:55
No. I have not tried. But I know what is the issue. If you call: SiteDirector-1, SiteDirector-2. You will not have an issue. I will have a look...

**Comment by andresailer** [comment] 2016-08-11 08:38
I think there was (or still is) something wrong with the script filling the Components and InstalledComponents.
When I install things with v6r15(p10) I get the named instance in the `InstalledComponents` table
```
mysql> select * from InstalledComponents where Instance like "SiteDirector%";
+-------------+--------+--------------------+---------------------+--------------------+-------------+---------------+
| ComponentID | HostID | Instance           | InstallationTime    | UnInstallationTime | InstalledBy | UnInstalledBy |
+-------------+--------+--------------------+---------------------+--------------------+-------------+---------------+
|          32 |      6 | SiteDirectorFoo    | 2016-08-11 08:31:40 | NULL               | sailer      | NULL          |
|          36 |      6 | SiteDirector       | 2016-02-04 12:29:12 | NULL               | sailer      | NULL          |
|          37 |      6 | SiteDirector       | 2016-02-04 12:29:12 | NULL               | sailer      | NULL          |
```
`SiteDirectorFoo` is the new one I just installed. The ones that were entered by the script are just called `SiteDirector` and point to a different `module` in the `Components` table.
```
mysql> select * from Components where Module like "SiteDirector%";
+-------------+--------------------+--------------------+-------+
| ComponentID | System             | Module             | Type  |
+-------------+--------------------+--------------------+-------+
|          32 | WorkloadManagement | SiteDirector       | agent |
|          33 | WorkloadManagement | SiteDirectorArc    | agent |
|          34 | WorkloadManagement | SiteDirectorCalice | agent |
|          35 | WorkloadManagement | SiteDirectorCream  | agent |
|          36 | WorkloadManagement | SiteDirectorHT     | agent |
|          37 | WorkloadManagement | SiteDirectorOSG    | agent |
+-------------+--------------------+--------------------+-------+
```

**Comment by andresailer** [comment] 2016-08-11 09:21
I fixed my table entries by hand and managed to uninstall what I wanted to uninstall.
Now one just hast figure out if other people are affected by this problem and how to deal with it.

**Comment by zmathe** [comment] 2016-08-11 09:41
There is few bugs. I am working on it since yesterday. The dirac-populate-component-db is correct. If you clean your db and run this script, the db content will be fine...
The content of the columns and the Instance should be swapped. I hope I will be able to found all the places where the db is filled wrongly...

**Comment by andresailer** [comment] 2016-08-11 09:44
So #3065 is not needed?

**Comment by zmathe** [comment] 2016-08-11 09:49
No. The fix is not needed. I already checked this script after cleaning the db I got the correct result. I found one bug (I was able to call a Module SiteDirector-1), which I already fixed, but there are other bug as well.

**Comment by zmathe** [comment] 2016-08-11 12:35
I have fixed the issue in #3068
For example:
[dzmathe.cern.ch]> install agent WorkloadManagement SiteDirector-1
Loading configuration template /afs/cern.ch/user/z/zmathe/cmtuser/DIRACv6r15p8/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
Can not find Agents/SiteDirector-1 in template
[ERROR] Can not find Agents/SiteDirector-1 in template
[dzmathe.cern.ch]> install agent WorkloadManagement SiteDirector
agent WorkloadManagement_SiteDirector is installed, runit status: Run
[dzmathe.cern.ch]> install agent WorkloadManagement SiteDirector-1 -m SiteDirector
Loading configuration template /afs/cern.ch/user/z/zmathe/cmtuser/DIRACv6r15p8/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
Adding to CS agent WorkloadManagement/SiteDirector-1
agent WorkloadManagement_SiteDirector-1 is installed, runit status: Run
[dzmathe.cern.ch]> install agent WorkloadManagement SiteDirector-2 -m SiteDirector
Loading configuration template /afs/cern.ch/user/z/zmathe/cmtuser/DIRACv6r15p8/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
Adding to CS agent WorkloadManagement/SiteDirector-2
agent WorkloadManagement_SiteDirector-2 is installed, runit status: Run
[dzmathe.cern.ch]> uninstall WorkloadManagement SiteDirector
Remove logs? y/[n] :
y
Successfully uninstalled WorkloadManagement/SiteDirector
[dzmathe.cern.ch]> uninstall WorkloadManagement SiteDirector-1
Remove logs? y/[n] :
y
Successfully uninstalled WorkloadManagement/SiteDirector-1
[dzmathe.cern.ch]> uninstall WorkloadManagement SiteDirector-2
Remove logs? y/[n] :

Successfully uninstalled WorkloadManagement/SiteDirector-2
[dzmathe.cern.ch]>

How to fix the db:
delete from HostLogging;
delete from InstalledComponents;
delete from Hosts;
delete from Components;
execute: dirac-populate-component-db using admin role.

**Comment by zmathe** [comment] 2016-08-11 13:26
I saw another possibility which can cause a problem. When we use dirac-setup-site and we have SiteDirector-1 in the local cfg file, then the Instance and Module will be the same according to the code: 
https://github.com/DIRACGrid/DIRAC/blob/integration/FrameworkSystem/Utilities/MonitoringUtilities.py#L17

**Comment by andresailer** [comment] 2016-08-11 15:01
The (unaltered) dirac-populate-component-db script still fills the InstalledComponents table with
```
|          95 |      4 | SiteDirector                | 2016-08-11 14:58:26 | NULL               | sailer      | NULL          |
|          96 |      4 | SiteDirector                | 2016-08-11 14:58:26 | NULL               | sailer      | NULL          |
|          97 |      4 | SiteDirector                | 2016-08-11 14:58:26 | NULL               | sailer      | NULL          |
|          98 |      4 | SiteDirector                | 2016-08-11 14:58:27 | NULL               | sailer      | NULL          |
```
While there should be `SiteDirectorName1`, `SiteDirectorName2`, etc. in this table, or not?

**Comment by zmathe** [comment] 2016-08-11 16:55
Yes. I did the following:
Database changed
mysql> delete from HostLogging;
Query OK, 3 rows affected (0.00 sec)

mysql> delete from InstalledComponents;
Query OK, 184 rows affected (0.01 sec)

mysql> delete from Hosts;
Query OK, 4 rows affected (0.00 sec)

mysql> delete from Components;
Query OK, 77 rows affected (0.00 sec)

and executed the populate script. After the db content:
mysql> select Instance, Module from InstalledComponents i, Components c where i.ComponentID=c.ComponentID;
+----------------------------------+-----------------------------+
| Instance                         | Module                      |
+----------------------------------+-----------------------------+
| SiteDirector-IN2P3               | SiteDirector                |
| SiteDirector-LAL                 | SiteDirector                |
| SiteDirector-OSC                 | SiteDirector                |
| SiteDirector-RAL                 | SiteDirector                |
| SiteDirector-RAL2                | SiteDirector                |
| SiteDirector-YANDEX              | SiteDirector                |
| StalledJobAgent                  | StalledJobAgent             |
| StalledJobAgent                  | StalledJobAgent             |
| StatesAccountingAgent            | StatesAccountingAgent       |

Something very strange in your side. What do you have under runit/WorkloadManagement?
and what do you have in the CS WorkloadManagement Agents section?

**Comment by zmathe** [comment] 2016-08-11 20:06
@andresailer I am sorry you already found the problem. We have also this script in LHCbDIRAC which working correctly and I was using and looking at that one. I am stupid I did not realised that I am in DIRAC. I committed the fix to #3068 as your PR is already deleted.

**Comment by andresailer** [comment] 2016-08-12 07:01
Ok, then I think everything is solved.

**Comment by fstagni** [comment] 2016-08-12 09:30
So, I close... maybe for the last time :)

**Closed by fstagni** 2016-08-12 09:30 UTC
Labels: Bug, Framework
