### ISSUE TITLE
Aliasing in the CS does not work with SE

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#988] opened 2012-10-12 21:59 UTC
I had a SE that was defined as
somesename
{ 
  Alias = someotherSEname
}
but the dirac-dms-lfn-replicas would never find the replica in that site. It needs the exact information.

**Comment by chaen** [comment] 2015-01-07 10:04
What is the desired behavior ? What would you like to see as the output of dirac-dms-lfn-replicas ? I haven't looked at aliases yet :-)

**Comment by sposs** [comment] 2015-01-07 10:47
I can't remember exactly what was the use case of this (2 years ago...). I think the idea was that in principle it's possible to assign aliases to resources and have many logical names that match one resource. If a SE changes its configuration because it changes for example its base path, I was thinking to add a new SE with the new configuration and replace the old SE configuration by an alias to the new config. Another example is the DIRAC SE, as it's easy to move the directory from one host to another: it's the same SE, not the same host... 
Also, on a more general point of view, the behaviour 'should' be homogeneous between the different parts of the CS: it's possible to alias any section with another, I think it should be true also for the SE.

**Comment by chaen** [comment] 2015-01-07 11:57
Okay, but in that case I am not the one to be assigned for this :-)

**Comment by sposs** [comment] 2015-01-07 12:11
That's the reason it was initially assigned to Andrei. The thing is: the issue is only a DMS one as far as I can tell, as it's the only one where the config is only partially taken from the CS.

**Comment by chaen** [comment] 2015-01-07 12:21
Okay but I don't really see where the problem is. You add a new file/replica at a given SE, so the DFC stores an entry on that given SE, it doesn't matter if it is an Alias or not ? 
Also, I don't clearly understand why you say that the SEManager should use getPfnForLfn ? First of all this method disappears in v6r13. And I am totally against calling any storage related method in catalog elements, and vice versa. If an operation involve both of them, then its place is by definition the DataManager.

But maybe I am completely off topic, sorry if that's the case :-)

**Comment by sposs** [comment] 2015-01-07 12:39
Actually, the initial problem is 2 years old, and I just remembered what the issue was. In the ILC VO, before using DIRAC, people were using the LFC and storing the files there. When I imported the files (LFC->DFC), there were some SEs that did not exist in DIRAC, and had a 'bad' name. I wanted to use the alias facilities to assign those 'strange' and unused SEs to properly defined DIRAC SEs so that in case some convention changed, I'd have only one place to look, and that would be the 'standard' SE. It did not work and I had to have 2 sections with the same info, but with different names. 
As for the second paragraph of your answer, I think you are not off topic as it used to be that the SE name and convention resolution were done in the FC (the SEManager). Off course, if that is different now, it's all for the best, but it does not solve the Alias issue which isn't the same behaviour as the one in the CS... It works just fine for CEs, not for SEs, and some consistency wouldn't hurt...

**Comment by chaen** [comment] 2015-01-07 12:46
Totally agree with the consistency. But as I said, I don't know all this alias business. I don't know what it does in the CE, I don't know what it does in the SE, and I don't know what it should be doing in the SE. If Andrei knows, he can take care. Otherwise, I'll dig into it

**Comment by chaen** [comment] 2016-01-21 14:27
Coming back to this long after. This seems to be a feature more than a bug. @phicharp has implemented an "inheritance" concept which looks more like what you want to do.

**Comment by chaen** [comment] 2018-08-01 09:31
Closing it as BaseSE and AliasSE are present

**Closed by chaen** 2018-08-01 09:31 UTC
Labels: Bug, DMS
