### ISSUE TITLE
v6r15 : VOMS2CSagent do not clean properly

### ISSUE THREAD

**Issue by closier** [DIRACGrid/DIRAC#3130] opened 2016-10-10 12:14 UTC
If a user had 2 certificates in VOMS and in the DIRAC registry and you remove one entry in VOMS, the entry in DIRAC registry is not remove.

example with bkhanji:
    /C=DE/O=GermanGrid/OU=UniHeidelberg/CN=Basem Khanji
    /C=IT/O=INFN/OU=Personal Certificate/L=Milano Bicocca/CN=basem KHANJI

THE INFN one has been deleted in VOMS but the modification has not been propagated to DIRAC CS.

**Comment by closier** [comment] 2016-10-25 12:35
There is an other thing which is break again. When a user has two certificate, a username_XXX is created instead of add the new certificate to the old one.
Why this regression ???

  Added new user ismith_1:
    DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ismith/CN=753762/CN=Iwan Thomas Smith
    CA: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    Email: iwan.smith@cern.ch
    Groups: ['lhcb_user']

**Comment by atsareg** [comment] 2016-11-06 21:10
The first issue is fixed in #3164. The second one I can not reproduce. Please check that the nickname is defined for the user. If not, it can result in having a name with _1 appended

**Comment by andresailer** [comment] 2017-04-06 09:26
Is this still known to be broken? Could it be that the VOMS server is not returning the attributes any more (since the update to voms admin 3.6.0?) but instead raises an exception on the server side?

Added a print out of result from attGetUserNickname:
```
{'CallStack': ['  File "/opt/dirac/pro/DIRAC/Core/scripts/dirac-agent.py", line 45, in <module>\n    agentReactor.go()\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Base/AgentReactor.py", line 146, in go\n    timeToNext = self.__scheduler.executeNextTask()\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Utilities/ThreadScheduler.py", line 133, in executeNextTask\n    self.__executeTask( taskId )\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Utilities/ThreadScheduler.py", line 186, in __executeTask\n    task[ \'func\' ]( *task[ \'args\' ] )\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 357, in am_go\n    cycleResult = self.__executeModuleCycle()\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 423, in __executeModuleCycle\n    result = self.am_secureCall( executors[0][0], executors[0][1] )\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 320, in am_secureCall\n    result = functor( *args )\n',
               '  File "/opt/dirac/pro/DIRAC/ConfigurationSystem/Agent/VOMS2CSAgent.py", line 86, in execute\n    result = self.__syncCSWithVOMS( vo, proxyUserName = voAdminUser, proxyUserGroup = voAdminGroup ) #pylint: disable=unexpected-keyword-arg\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Utilities/Proxy.py", line 83, in wrapped_fcn\n    return fcn( *args, **kwargs )\n',
               '  File "/opt/dirac/pro/DIRAC/ConfigurationSystem/Agent/VOMS2CSAgent.py", line 312, in __syncCSWithVOMS\n    result = vomsSrv.attGetUserNickname( dn, vomsUserDict[dn][\'CA\'] )\n',
               '  File "/opt/dirac/pro/DIRAC/Core/Security/VOMSService.py", line 131, in attGetUserNickname\n    return S_ERROR( DErrno.EVOMS, "Error in function getUserNickname: %s" % e )\n'],
 'Errno': 1121,
 'Message': "VOMS Error ( 1121 : Error in function getUserNickname: Server raised fault: 'java.lang.ClassCastException: org.glite.security.voms.admin.persistence.model.attribute.VOMSUserAttribute cannot be cast to org.glite.security.voms.admin.persistence.model.attribute.VOMSBaseAttribute')",
 'OK': False}
```

**Comment by closier** [comment] 2017-04-06 09:48
The Author of VOMS is looking at it..

**Comment by closier** [comment] 2017-04-06 11:01
Comment from the developer:
Hello Joel, 

it's a bug introduced with VOMS Admin 3.6.0.
I am working on a fix.

Cheers,
Andrea

**Comment by andresailer** [comment] 2017-05-16 09:29
Is there a new release of the VOMS admin server now or still just a release candidate?

**Comment by fstagni** [comment] 2017-07-04 08:01
If I look in https://github.com/italiangrid/voms-admin-server the last tag is still 3.6.0.

**Comment by andresailer** [comment] 2017-07-04 08:05
Desy has installed the 3.6.1rc1 release candidate, so the VOMS2CSAgent is working again with the user attribute for us.

**Comment by closier** [comment] 2017-07-04 08:15
As we do not manage ourself the VOMS server,  I am not following the version of VOMS-ADMIN

**Comment by fstagni** [comment] 2017-07-04 09:43
Yes of course. It was just to get some comments on this task, which I think that, due to the responses, can now be closed.

**Closed by fstagni** 2017-07-04 09:43 UTC
Labels: Bug
