### ISSUE TITLE
Dirac fails to handle MySQL passwords correctly (at-least at bootstrap)

### ISSUE THREAD

**Issue by raowenqmul** [DIRACGrid/DIRAC#5620] opened 2021-11-18 13:43 UTC
Hello, 
MySQL 8 enforces password complexity rules.
As a result I chose a MySQL Dirac user  password containing the '@' symbol: `TestPass@X9`
I then ran:
` ./install_site.sh --debug -v v7r3p9 install-v7r3p9.cfg 2>&1 > install-v7r3p9.log
`
There were errors which I grep'd out of the log file:
```
2021-11-18 12:58:25 UTC Framework/ComponentMonitoring ERROR: Could not connect to the database : (_mysql_exceptions.OperationalError) (2005, "Unknown MySQ server host 'X9@localhost' (2)")
2021-11-18 12:58:25 UTC Framework/ComponentMonitoring ERROR: Could not connect to the database : (_mysql_exceptions.OperationalError) (2005, "Unknown MySQ server host 'X9@localhost' (2)")
OperationalError: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'X9@localhost' (2)")
2021-11-18 12:58:37 UTC ResourceStatus/ResourceStatus ERROR: Exception while calling initialization function: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'X9@localhost' (2)")
OperationalError: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'X9@localhost' (2)")
2021-11-18 12:58:37 UTC ResourceStatus/ResourceStatus ERROR: Exception while calling initialization function: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'X9@localhost' (2)")

```

So I changed to using '%' instead: `TestPass%X9`
This resulted in errors in the log like this:

```
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Dirac'@'localhost' (using password: YES)")
2021-11-18 13:22:55 UTC ResourceStatus/ResourceStatus ERROR: Exception while calling initialization function: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Dirac'@'localhost' (using password: YES)")
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Dirac'@'localhost' (using password: YES)")
2021-11-18 13:22:55 UTC ResourceStatus/ResourceStatus ERROR: Exception while calling initialization function: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Dirac'@'localhost' (using password: YES)")

```

I then changed to using  '-' symbol instead and all proceeded smoothly.

I was less precise about collecting data for the MySQL root user account. I know that '%' works for root but I **think** there may have been problems with '@' but can not recall.

Brief Analysis:
There is some less than robust string handling for MySQL passwords at least in the bootstrap code, possibly more widely.

The '@' symbol is clearly confused by the python code possibly with the '@' symbol used by MySQL to separate user and domain as in the SQL statement:
`CREATE USER 'Dirac'@'localhost' IDENTIFIED BY 'diracpass';
`
Hence the error: `Unknown MySQ server host 'X9@localhost' ` where the X9 is the part of the password string following the '@' sign in the password but is interpreted as the database username... Strange!

The '%' symbol is perhaps more subtle. I wonder if %-formating or other python string formatting is messing with and % in a password string.

Work around:
Avoid '@' in MySQL passwords (Dirac user and root user)
Avoid '%' in Dirac users MySQL password.
The '-' symbol appears to be safe.

I hope that the above is sufficient to recreate the issue and useful to track down and fix the issue.

Regards
Alex Owen

**Comment by fstagni** [comment] 2021-11-18 16:48
Thanks for the report! We'll take care.

**Comment by fstagni** [comment] 2022-10-04 08:43
I have not found the source of this, at least not using py3. I see you were trying with what is today a rather old py2 version of DIRAC. I suspect the error might be there can't prove it. Have you by change tried again?

**Comment by fstagni** [comment] 2022-10-26 05:33
Closing as I believe solved already.

**Comment by chrisburr** [comment] 2022-10-26 06:53
The issue is here:
https://github.com/DIRACGrid/DIRAC/blob/85a8918df0cdd1c0a03123f7d746dda060becffa/src/DIRAC/FrameworkSystem/DB/InstalledComponentsDB.py#L328-L332
See: https://docs.sqlalchemy.org/en/14/core/engines.html#escaping-special-characters-such-as-signs-in-passwords

**Comment by fstagni** [comment] 2022-10-28 09:35
Good catch! I just made a PR, have a look.

**Comment by fstagni** [comment] 2022-11-02 11:47
Fixed by https://github.com/DIRACGrid/DIRAC/pull/6468

**Closed by fstagni** 2022-11-02 11:47 UTC
Labels: Bug, Core
