### ISSUE TITLE
Replace coveralls with codecov

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRAC#3971] opened 2019-02-22 08:54 UTC
I propose that we switch from coveralls to codecov because:

- `python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.2 which is incompatible`

- you can see which new lines of a PR are tested and which are not, quite helpfull

**Comment by fstagni** [comment] 2019-03-18 19:25
Duplicate of #3984, closing this one.

**Closed by fstagni** 2019-03-18 19:25 UTC
