### ISSUE TITLE
Reject long filenames rather than registering requests

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6543] opened 2022-11-14 07:59 UTC
We've had a handful of cases of REA requests being stuck looping due to long filenames like:

```
/lhcb/user/a/auser/2022_11/685221/685221888/13TeV__Z__POWHEGewPythia__8245__NNPDF31_nlo_as_0118__0__as0.118000_IKT1.000000_s2tw0.228__evts31853__seed1467__lhcbacceptance.root
```

DIRAC should just outright reject such filenames.

**Comment by marianne013** [comment] 2022-11-14 09:49
I'm glad to see that it's not our 'small' communities that attempt to encode all their metadata in their file names :-D

**Comment by chaen** [comment] 2024-05-06 12:01
Duplicate of https://github.com/DIRACGrid/DIRAC/issues/7602

**Closed as completed by chaen** 2024-05-06 12:01 UTC
Labels: Bug, DMS
