### ISSUE TITLE
[v6r20] ReportGenerator for Users is obtaining jobs for all users

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3776] opened 2018-08-02 12:21 UTC
When a user is using the accounting application to draw, e.g., the cumulative number of jobs the plot instead shows the jobs of all users.

![cumuljobs-bysite-june-july-2018](https://user-images.githubusercontent.com/2115797/43583042-944dbf66-965e-11e8-8651-5815ab2585bc.png)

When I draw as admin, where I can select the specific user, I get the proper result.

![cumuljobs-bysite-june-july-2018_justuser](https://user-images.githubusercontent.com/2115797/43583069-a71c49be-965e-11e8-82b4-8af3beea3f17.png)

I am not sure if the problem is that the webapp needs to force the username into the selection condition (which I don't know where it happens), or if the ReportGenerator JobPolicy function should force the User to be in the selection condition.
I.e., this should always set the 'User' entry to userName ?
https://github.com/DIRACGrid/DIRAC/blob/41989c6c5622bceb64ccdc1e9770ba4c8e2d23ec/AccountingSystem/private/Policies/JobPolicy.py#L48-L58

**Comment by fstagni** [comment] 2018-08-06 11:31
Do you need an urgent reply? Otherwise I just assign to Zoltan (he's on holiday right now)

**Comment by andresailer** [comment] 2018-08-06 11:44
Thanks. I have hot fixed the JobPolicy, so not urgent.

**Comment by zmathe** [comment] 2018-09-13 15:20
We can call it a bug, but as far as I remember it is by design: the user can see all running jobs, but can not see the owner of the jobs. I am fine to always add the username to the condDict, but it will have side effects:
-Accounting can be accessible without certificate (using http) for the external persons like site administrators. The site administrators want to see how many jobs we are running in the Grid, which is I think fine. Because  we do not allow them to see the owners of the jobs.
-can not send the url of a given plot to an external people (this is happened when we want to integrate our accounting plots to BOINC)

**Comment by andresailer** [comment] 2018-09-13 15:37
Can't the user only see all jobs if the group has the JobSharing attribute, which is treated in the lines before the NORMAL_USER property, 
https://github.com/DIRACGrid/DIRAC/blob/41989c6c5622bceb64ccdc1e9770ba4c8e2d23ec/AccountingSystem/private/Policies/JobPolicy.py#L39-L47

and if the accounting is accessed without a certificate, than the `Properties.NORMAL_USER` condition is not met, is it? So it goes here
https://github.com/DIRACGrid/DIRAC/blob/41989c6c5622bceb64ccdc1e9770ba4c8e2d23ec/AccountingSystem/private/Policies/JobPolicy.py#L59-L67

**Comment by zmathe** [comment] 2018-09-14 07:31
Yes, you are right. The host property is used when the accounting accessed by http. 
But then the user which has certificate only can see his/her jobs in different sites and the user without certificate can see all jobs running in different site. This is inconsistent no? But thinking further probably the user who has certificate wants to see only his/her job. Please create a PR and other people can also have also opinion. I am fine to change the current behaviour.

**Closed** 2018-09-21 12:05 UTC
